name: Create Icons

on:
  workflow_dispatch:
  push:
    paths:
      - '**/icon.svg'

jobs:
  build:
    name: Create Icons
    runs-on: ubuntu-latest
    steps:

# CHECKOUT CODE
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2

# CREATE ICONS
    - id: create-icons
      name: Create icons for different platforms
      run: |
        # Create icons for different platforms
        convert -version
        convert -background transparent -density 1000 \
        -resize 64x64 \
        icon.svg \
        icon.png
        convert -background transparent -density 1000 \
        -define icon:auto-resize -colors 256 \
        icon.svg \
        icon.ico

    - id: upload-icons
      name: Upload generated icons
      uses: actions/upload-artifact@v2
      with:
        name: icons
        path: ./icon.*

    - id: push-icons
      name: Commit icons to repository
      run: |
        # Commit icons to repository
        git config --global user.name "Sualeh Fatehi"
        git config --global user.email "sualeh@hotmail.com"
        git add ./icon.*
        git commit -m "Create icons for different platforms"
        git push
