name: Create Icons

on: workflow_dispatch

jobs:
  build:
    name: Create Icons
    runs-on: ubuntu-latest
    steps:

# CHECKOUT CODE
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2

# CREATE ICONS
    - id: create-icons
      name: Create icons
      run: |
        # Create icons
        convert -version
        convert -background none -density 64 -resize 64x64 \
        ./consoleapp/src/installer/icons/icon.svg \
        ./consoleapp/src/installer/icons/icon.png

    - id: upload-icons
      name: Upload generated icons
      uses: actions/upload-artifact@v2
      with:
        name: icons
        path: ./consoleapp/src/installer/icons/icon.*
