name: Create Icons

on: workflow_dispatch

jobs:
  build:
    name: Create Icons
    runs-on: ubuntu-latest
    steps:

# CHECKOUT CODE
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2

# CREATE ICONS
    - id: build
      name: Build distribution
      run: |
        convert -version
