name: Create Icons

on: workflow_dispatch

jobs:
  build:
    name: Create Icons
    runs-on: ubuntu-latest
    steps:

# SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15

# BUILD FOR DISTRIBUTION
    - id: build
      name: Build distribution
      run: |
        sudo apt-get -qq update
        sudo apt-get -q install imagemagick
        convert -version
